# Generated by Django 5.0.6 on 2026-06-04 21:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('subdomain', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('official_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'colleges',
            },
        ),
        migrations.CreateModel(
            name='CollegeSubscription',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('entitlements_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'college_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('module_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'feature_catalog',
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3'), ('gcs', 'GCS'), ('azure', 'Azure'), ('other', 'Other')], default='local', max_length=30)),
                ('storage_key', models.TextField()),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('asset_kind', models.CharField(choices=[('profile_photo', 'Profile Photo'), ('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('general', 'General')], default='general', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'file_assets',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_features',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('void', 'Void')], default='issued', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_invoices',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_ref', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], max_length=30)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='successful', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'subscription_payments',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CollegeSettings',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='platforms.college')),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('academic_year_start_month', models.PositiveSmallIntegerField(default=7)),
                ('feature_overrides', models.JSONField(blank=True, default=dict)),
                ('settings_jsonb', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'college_settings',
            },
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['status'], name='idx_colleges_status'),
        ),
        migrations.AddField(
            model_name='collegesubscription',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_assets', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_plans', to='platforms.feature'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoices', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='platforms.collegesubscription'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='platforms.subscriptioninvoice'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='platforms.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='collegesubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='college_subscriptions', to='platforms.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='collegesettings',
            name='logo_file_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_logo_for', to='platforms.fileasset'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['college'], name='idx_file_assets_clg_id'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['uploaded_by'], name='idx_file_user'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['college', 'status', 'due_date'], name='idx_subinv_stat'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.UniqueConstraint(fields=('college', 'invoice_no'), name='uq_subscription_invoice_no_per_college'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['invoice'], name='idx_subpay_inv'),
        ),
        migrations.AddIndex(
            model_name='planfeature',
            index=models.Index(fields=['feature'], name='idx_plan_features_feature_id'),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='uq_plan_feature'),
        ),
        migrations.AddIndex(
            model_name='collegesubscription',
            index=models.Index(fields=['college', 'status'], name='idx_colsub_stat'),
        ),
        migrations.AddConstraint(
            model_name='collegesubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['trial', 'active', 'past_due'])), fields=('college',), name='uq_one_active_subscription_per_college'),
        ),
    ]
