# Generated by Django 5.0.6 on 2026-06-04 21:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('exam', 'Exam'), ('library', 'Library'), ('hostel', 'Hostel'), ('transport', 'Transport'), ('lab', 'Lab'), ('misc', 'Misc')], max_length=30)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_optional', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_heads', to='platforms.college')),
            ],
            options={
                'db_table': 'fee_heads',
            },
        ),
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('part_paid', 'Part Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='issued', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='platforms.college')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_fee_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fee_invoices',
            },
        ),
        migrations.CreateModel(
            name='FeeInvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('void', 'Void')], default='active', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoice_items', to='platforms.college')),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='finance.feehead')),
                ('fee_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.feeinvoice')),
            ],
            options={
                'db_table': 'fee_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], max_length=30)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='successful', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='platforms.college')),
                ('fee_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.feeinvoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_fee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fee_payments',
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.academicyear')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='platforms.college')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.program')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.section')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.term')),
            ],
            options={
                'db_table': 'fee_structures',
            },
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_items', to='platforms.college')),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_items', to='finance.feehead')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.feestructure')),
            ],
            options={
                'db_table': 'fee_structure_items',
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_accounts', to='platforms.college')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_accounts', to='finance.feestructure')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_account', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'student_fee_accounts',
            },
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='student_fee_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.studentfeeaccount'),
        ),
        migrations.AddConstraint(
            model_name='feehead',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='uq_fee_head_code_per_college'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoiceitem',
            constraint=models.UniqueConstraint(fields=('fee_invoice', 'fee_head'), name='uq_fee_invoice_item_per_head'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['fee_invoice'], name='idx_fee_payments_invoice_id'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(fields=('college', 'receipt_no'), name='uq_fee_receipt_no_per_college'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['college', 'program', 'academic_year'], name='idx_feestr_prog'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('college', 'academic_year', 'program', 'section', 'name'), name='uq_fee_structure_per_scope_name'),
        ),
        migrations.AddConstraint(
            model_name='feestructureitem',
            constraint=models.UniqueConstraint(fields=('fee_structure', 'fee_head'), name='uq_fee_structure_item_per_head'),
        ),
        migrations.AddIndex(
            model_name='studentfeeaccount',
            index=models.Index(fields=['college'], name='idx_stdfee_col'),
        ),
        migrations.AddConstraint(
            model_name='studentfeeaccount',
            constraint=models.UniqueConstraint(fields=('student',), name='uq_one_fee_account_per_student'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['student_fee_account'], name='idx_fee_invoices_account_id'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['college', 'status', 'due_date'], name='idx_feeinv_due'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(fields=('college', 'invoice_no'), name='uq_fee_invoice_no_per_college'),
        ),
    ]
