# Generated by Django 5.0.6 on 2026-06-04 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='batch',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='batch',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='program',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.program'),
        ),
        migrations.AddField(
            model_name='section',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='section',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.section'),
        ),
        migrations.AddField(
            model_name='subject',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.department'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='academics.section'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_offerings', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='term',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='academics.term'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='platforms.college'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='subject_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.subjectoffering'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('college', 'name'), name='uq_academic_year_name_per_college'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('college',), name='uq_current_academic_year_per_college'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['college'], name='idx_dprtmts_col_id'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='uq_department_code_per_college'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['college'], name='idx_programs_col_id'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='uq_program_code_per_college'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['program', 'academic_year'], name='idx_batches_program_year'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('college', 'program', 'academic_year', 'name'), name='uq_batch_per_program_year_name'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['batch'], name='idx_sections_batch_id'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('college', 'batch', 'name'), name='uq_section_name_per_batch'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section'], name='idx_enroll_section_id'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='idx_enroll_stdt_id'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('college', 'student', 'academic_year'), name='uq_student_per_academic_year_per_college'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('college', 'section', 'roll_no'), name='uq_roll_no_per_section_per_college'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['college'], name='idx_subjects_col_id'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='uq_subject_code_per_college'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['academic_year'], name='idx_terms_academicyear_id'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term_no'), name='uq_term_no_per_academic_year'),
        ),
        migrations.AddIndex(
            model_name='subjectoffering',
            index=models.Index(fields=['section'], name='idx_suboff_sec'),
        ),
        migrations.AddIndex(
            model_name='subjectoffering',
            index=models.Index(fields=['teacher'], name='idx_suboff_tchr'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(fields=('college', 'section', 'subject', 'term'), name='uq_subject_offering_per_section_subject_term'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['college', 'day_of_week'], name='idx_tt_entries_clg_day'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('subject_offering', 'day_of_week', 'start_time'), name='uq_timetable_entry_per_offering_day_start'),
        ),
    ]
