# Generated by Django 5.0.6 on 2026-06-04 21:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('attachment_file_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_attachments', to='platforms.fileasset')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='platforms.college')),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to='accounts.teacherprofile')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subjectoffering')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_text', models.TextField(blank=True, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.assignment')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='platforms.college')),
                ('file_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_submissions', to='platforms.fileasset')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'assignment_submissions',
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('note', 'Note'), ('pdf', 'PDF'), ('link', 'Link'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_url', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('teachers', 'Teachers'), ('section', 'Section')], default='students', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='platforms.college')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_materials', to=settings.AUTH_USER_MODEL)),
                ('file_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_materials', to='platforms.fileasset')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='academics.subject')),
                ('subject_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='academics.subjectoffering')),
            ],
            options={
                'db_table': 'course_materials',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience_scope', models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('teachers', 'Teachers'), ('staff', 'Staff'), ('section', 'Section'), ('role', 'Role')], max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='platforms.college')),
                ('file_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='platforms.fileasset')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_notices', to=settings.AUTH_USER_MODEL)),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='accounts.role')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='academics.section')),
            ],
            options={
                'db_table': 'notices',
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['subject_offering'], name='idx_asg_suboff'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student'], name='idx_asgsub_std'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='uq_assignment_submission_per_student'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['subject_offering'], name='idx_course_mat_suboff_id'),
        ),
        migrations.AddConstraint(
            model_name='coursematerial',
            constraint=models.CheckConstraint(check=models.Q(('subject_offering__isnull', False), ('subject__isnull', False), _connector='OR'), name='ck_course_material_subject_ref'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['college', 'status', 'publish_at'], name='idx_notices_clg_status_dt'),
        ),
    ]
