# Generated by Django 5.0.6 on 2026-06-04 21:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('unit', 'Unit'), ('quiz', 'Quiz'), ('midterm', 'Midterm'), ('final', 'Final'), ('practical', 'Practical'), ('other', 'Other')], max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('conducted', 'Conducted'), ('result_declared', 'Result Declared'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicyear')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='platforms.college')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.section')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.term')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('held', 'Held'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='platforms.college')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='exams.exam')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='academics.subjectoffering')),
            ],
            options={
                'db_table': 'exam_papers',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grade_label', models.CharField(blank=True, max_length=10, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='platforms.college')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_exam_results', to=settings.AUTH_USER_MODEL)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exampaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'exam_results',
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_label', models.CharField(max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='platforms.college')),
            ],
            options={
                'db_table': 'grading_scales',
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['college', 'section'], name='idx_exams_college_section'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['exam'], name='idx_exam_papers_exam_id'),
        ),
        migrations.AddConstraint(
            model_name='exampaper',
            constraint=models.UniqueConstraint(fields=('exam', 'subject_offering'), name='uq_exam_paper_per_exam_subject'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student'], name='idx_exam_std'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam_paper', 'student'), name='uq_exam_result_per_paper_student'),
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.UniqueConstraint(fields=('college', 'grade_label'), name='uq_grade_label_per_college'),
        ),
    ]
